GET http://localhost:8888/api/services/1
Accept: application/json

###

GET http://localhost:8888/api/customers
Accept: application/json

###

DELETE http://localhost:8888/api/customers/3
Accept: application/json

###

POST http://localhost:8888/api/customers
Content-Type: application/json

{
  "name": "Petya",
  "birth_date": "2011-11-11",
  "notes": "Customer"
}

###

PUT http://localhost:8888/api/customers/8
Content-Type: application/json

{
  "birth_date": "1988-11-11"
}

###
